spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/init.xml
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970